### ISSUE TITLE
Stages are reset everytime a piece is moved

### ISSUE THREAD

**Issue by zeroinformatique** [xytovl/SmartStage#1] opened 2015-09-17 15:15 UTC
Smart stage sorts the stages correctly, but as soon as I move any piece on the ship, all the stage will reset to their previous position. 

This is very annoying since I'm never really sure if the stages are correct or not. It gets especially tricky when you lock fuel tanks to test the center of gravity and can't use SmartStage because it thinks the tanks are empty.

Saving and reloading the ship after using SmartStage fixes the issue temporaly.

**Comment by xytovl** [comment] 2015-09-17 16:11
Are you using the "Automatically recompute staging" option ? This is configurable in the window that opens when you click the smartstage icon. The icon turns green when the option is selected.
In automatic mode, staging is computed on each ship modification.

**Comment by zeroinformatique** [comment] 2015-09-17 22:07
I never use "Automatically recompute staging" because I often want to tune the staging system after SmartStage.
It does a great job at "preparing" the staging, but it often isn't perfect for large complex vessels.

**Comment by xytovl** [comment] 2015-09-18 19:24
Can you try with no mod installed and provide steps to reproduce ?
If I try on any ship, it only changes staging if I click the button or if I am in auto mode.

**Comment by zeroinformatique** [comment] 2015-09-19 00:42
I did many tests to find the step to reproduce, and it's "slightly" random (but frequent)
It occurs a lot more frequently with a parachute on the last stage.

Here a video : https://home.griffox.info/~OzoneGrif/SmartStage.mp4
You can read the video with Chrome if you have it.

Notice how the pieces (especially the reactor) get sometimes completely on the wrong stage.

**Comment by xytovl** [comment] 2016-05-04 06:18
Closing as staging logic has changed in 1.1, if the issue still exists the causes will be different I guess

**Closed as completed by xytovl** 2016-05-04 06:18 UTC
